---
title: "creating-maps-in"
output: html_document
date: '2022-12-17'
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

library(tidycensus)

data <- get_acs(geography= "tract",
state = "DC",
variables=c(
medianIncome= "B19013_001"),
year = 2019,
survey = "acs5",
output="wide",
geometry=TRUE)

data2 <- get_acs(geography= "tract",
state = "TX",
variables=c(
medianIncome= "B19013_001"),
year = 2019,
survey = "acs5",
output="wide",
geometry=TRUE)


```

## Mapview

```{r}

library(mapview)

# mapviewOptions(fgb = FALSE)


mapviewMap <- mapview(data, zcol=c("medianIncomeE"), legend = TRUE,
                      hide = TRUE)

mapviewMap2 <- mapview(data2, zcol=c("medianIncomeE"), legend = TRUE,
                      hide = TRUE)
mapviewMap
mapviewMap2

```



```{r}

# Call the color function (colorNumeric) to create a new palette function
pal <- colorNumeric(c("red", "green", "blue"), 1:10)
# Pass the palette function a data vector to get the corresponding colors
pal(c(1,6,9))

```


## Leaflet Map

```{r}

# from: https://rstudio.github.io/leaflet/choropleths.html

library(leaflet)
library(viridis)
library(RColorBrewer)
library(fixest)
library(tidyverse)
library(htmltools)
library(priceR)

data <- data %>% 
  drop_na()


bins <- c(0, 49000, 93999, 119999, Inf)
labels <- c("< $49,000", "$49,000 - $93,999", "$94,000 - $119,000", "> $119,999")
pal <- colorBin("YlGnBu", domain = data$medianIncomeE, bins = bins)
tooltip_label <- sprintf(
  "<strong> %s </strong> <br/> <strong> Median Income: </strong> %s",
  data$NAME, format_dollars(data$medianIncomeE)) %>% 
  lapply(htmltools::HTML)

# pal <- colorNumeric(palette = "Blues",domain = data$medianIncomeE)

leafletMap <-leaflet() %>%
  addProviderTiles("CartoDB.Positron", 
                 group = "Positron") %>%
  addPolygons(data = data,
              fillColor = ~pal(data$medianIncomeE),
              weight = 2,
              opacity = 1,
              color = "#5e5c5c",
              dashArray = "3",
              fillOpacity = 0.55,
              highlightOptions = highlightOptions(
                 weight = 5,
                 color = "#666",
                 dashArray = "",
                 fillOpacity = 0.7,
                 bringToFront = TRUE),
              label = tooltip_label,
                labelOptions = labelOptions(
                  style = list("font-weight" = "normal", padding = "3px 8px"),
                  textsize = "15px",
                  direction = "auto")) %>%
  addLegend(pal = pal,
            values = data$medianIncomeE,
            position = "bottomright",
            title = "Median Income",
            labFormat = function(type, cuts, p) {paste0(labels)})

leafletMap


```

```{r}

# from: https://www.prb.org/resources/making-sense-of-geospatial-data-with-r/


data2 <- data2 %>% 
  drop_na()

bins2 <- c(0,50000,100000,150000,200000,250000)
pal2 <- colorBin("RdYlBu", domain = data2$medianIncomeE, bin = bins2)
labels2 <- c("< $49,999", "$50,000 - $99,999", "$100,000 - $149,999", "$150,000 - $199,999", "$200,000- 250,000")
tooltip_label2 <- sprintf(
  "<strong> %s </strong> <br/> <strong> Median Income: </strong> %s",
  data2$NAME, format_dollars(data2$medianIncomeE)) %>% 
  lapply(htmltools::HTML)

leafletMap2 <-leaflet() %>%
  addProviderTiles("CartoDB.Positron", 
                 group = "Positron") %>%
  addPolygons(data = data2,
              fillColor = ~pal2(data2$medianIncomeE),
              weight = .05,
              opacity = 1,
              color = "#5e5c5c",
              dashArray = "",
              fillOpacity = 0.55,
              highlightOptions = highlightOptions(
                 weight = 5,
                 color = "#666",
                 dashArray = "",
                 fillOpacity = 0.7,
                 bringToFront = TRUE),
              label = tooltip_label2,
              labelOptions = labelOptions(
                  style = list("font-weight" = "normal", padding = "3px 8px"),
                  textsize = "15px",
                  direction = "auto")) %>%
  addLegend(pal = pal2,
            values = data2$medianIncomeE,
            position = "bottomright",
            title = "Median Income",
            labFormat = function(type, cuts, p) {paste0(labels2)})

leafletMap2
```


## With GGPlot

```{r}

library(ggplot2)

data2 %>%
  ggplot(aes(fill = medianIncomeE)) + 
  geom_sf(color = NA) + 
  scale_fill_viridis_c(option = "mako") 

```

## Zipcodes

```{r}

data3 <- get_acs(geography= "zip code tabulation area",
                 state = "TX",
                 variables=c(medianIncome= "B19013_001"),
                 year = 2019,
                 survey = "acs5",
                 output="wide",
                 geometry=TRUE)


data3 %>%
  drop_na() %>%
  ggplot(aes(fill = medianIncomeE)) + 
  geom_sf(color = NA) + 
  scale_fill_viridis_c(option = "mako") 

```




